spring:
  application:
    name: hgp-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认180000（3分钟）
      idle-timeout: 180000
      min-pool-size: 10
      # 连接池最大连接数，默认是50
      maximum-pool-size: 50
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      validation-timeout: 20000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# MySQL和h2的比较，在spring.datasource.hikari.min-pool-size=10和spring.datasource.hikari.maximum-pool-size=50的参数比较
# 可能h2用到是内存数据库，响应比较快，1000个线程用hikari数据库连接时，没有抛出 HikariPool-1 - Connection is not available, request timed out after 10000ms. 这种异常
# 用MySQL时，1000个线程用hikari数据库连接时，抛出 HikariPool-1 - Connection is not available, request timed out after 10000ms. 异常 以及 org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection 异常
# 把配置参数改成 spring.datasource.hikari.min-pool-size=300和spring.datasource.hikari.maximum-pool-size=1000，不再抛数据链接数据异常，但是发现一轮秒杀，1000个线程抢100件商品，每个线程只能抢一件，发现只有十几个线程抢到商品
server:
  port: 8085
